name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Maven
        run: mvn clean install

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.SECRET_USERNAME }} --password-stdin

      - name: Build Docker Image and Push
        run: |
          docker buildx create --use
          docker buildx build -t jagadeeshb1585/clockbox:latest --push .
          # Replace "your-docker-username" with your actual Docker Hub username.

    
